version: '3.0'

services:
    udp:
        image: udp_server
        ports:
            - "5001:5001"
        volumes:
            - ./udp_server:/home
            - ./common:/home/common
        networks:
            - internal
        depends_on:
            - db
    web:
        build: frontend/
        image: flask_frontend
        ports: 
            - "5000:5000"
        volumes: 
            - ./frontend:/home
            - ./common:/home/common
        networks:
            - internal
        depends_on: 
            - db
    
    db:
        image: mariadb
        #ports: 
        #    - "3306:3306"
        networks:
            - internal
        volumes:
            - ./database:/home
        environment: 
            - MYSQL_ROOT_PASSWORD=pass

    

networks:
    internal:
