from fedora:31

RUN mkdir /root/.ssh && touch /root/.ssh/authorized_keys && \
	echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDzYfskc4uDBaiMF30maNv6jc8K/5zpQarLIIDLZGTFqmkwyyV4hJUlJwrNYl3cik+JbPWGunrj1Tp6Fdo6gjNmMGD3+CK9iXrxxy55QkXOM1r0fRBqRLZC6XCQGhZhLacMxcNopy3+wR2IEm6w0z2ZdnjRexO1Is8RHkxeS08g43kE9xnc9ZVdMtzvdfWn64qW30OKXS5vDyV65p16db+6n2V1c30lW3HzApSTAJuSjbMfbh54MK1ar6yLzl/mH0lwYtrLXBo43YsTPN6vsfbRYQu+236ysj2S57+6eEo8iLFFzPRF+1m3RfljOc7PGLil7XYEzOiJoOQlxT1ep2VEhuXWBQUSimHQbBeUf38Xhf9KnD7pK/SIZw65GP6AIenl4RL1jqqro0++qUatClOSHIdA9BzFktPioov84w60wXH4nFwa70hoUCXhaPLDIxBHpMsapSFKA22MSdS3C7fkJutfDnh4VPvyw9zG+7qkssRejRm7+W40i3fVTkTK1Vs= pablo@localhost.localdomain" > /root/.ssh/authorized_keys && \
	chmod 700 /root/.ssh && chmod 600 /root/.ssh/authorized_keys && \
	touch /usr/local/etc/sshd_config && useradd sshd && \
	echo "root:root" | chpasswd

RUN dnf update -y
RUN dnf install make -y && \
	dnf install autoconf -y && \
	dnf install gcc -y && \
	dnf install g++ -y && \
	dnf install zlib-devel -y && \
	dnf install openssl-devel -y && \
	dnf install gdb -y && \
	dnf install mysql-devel -y && \
	dnf install procps -y && \
	dnf install tcpdump -y && \
	dnf install libsodium-devel -y

